/**
 * Static content for the per-location "Content Library" page (+ its
 * Playlists tab). Thumbnails are real photos from Pexels (free to use, no
 * attribution required) — verified these specific IDs resolve before using
 * them; every other page in this business section uses icon placeholders
 * instead of external images, this one is a deliberate exception per the
 * user's explicit ask. Nothing here is wired to Supabase yet.
 */
import type { StatItem } from "@/components/business/stat-tile";
import { FileText, HardDrive, Image as ImageIcon, Music, Video } from "lucide-react";

export const LOCATION_NAME = "Nairobi CBD";

function pexels(id: number): string {
  return `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=800`;
}

export const CONTENT_STATS: StatItem[] = [
  { key: "total", label: "Total Content", value: "428", sublabel: "All media", icon: HardDrive, color: "violet" },
  { key: "videos", label: "Videos", value: "162", sublabel: "37.9%", icon: Video, color: "blue" },
  { key: "images", label: "Images", value: "184", sublabel: "43.0%", icon: ImageIcon, color: "emerald" },
  { key: "audio", label: "Audio", value: "52", sublabel: "12.1%", icon: Music, color: "amber" },
  { key: "documents", label: "Documents", value: "30", sublabel: "7.0%", icon: FileText, color: "fuchsia" },
  { key: "storage", label: "Storage Used", value: "32.6 GB", sublabel: "of 100 GB", icon: HardDrive, color: "pink" },
];

export type ContentType = "video" | "image" | "audio" | "document";
export type ContentStatus = "approved" | "pending" | "rejected";

export interface ContentItem {
  id: string;
  title: string;
  type: ContentType;
  format: string;
  thumbnail: string | null;
  duration: string | null;
  sizeMb: number;
  resolution: string | null;
  status: ContentStatus;
  tag: string;
  description: string;
  uploadedBy: string;
  uploadedAgo: string;
  usedInPlaylists: number;
  usedInSchedules: number;
}

export const CONTENT_ITEMS: ContentItem[] = [
  {
    id: "c1",
    title: "Happy Hour Promo",
    type: "video",
    format: "MP4",
    thumbnail: pexels(4762719),
    duration: "00:15",
    sizeMb: 7.2,
    resolution: "1920×1080",
    status: "approved",
    tag: "Promotions",
    description: "Promotional video for happy hour discounts from 4PM to 7PM.",
    uploadedBy: "Michael W.",
    uploadedAgo: "2 days ago",
    usedInPlaylists: 3,
    usedInSchedules: 12,
  },
  {
    id: "c2",
    title: "New Menu – Burger",
    type: "video",
    format: "MP4",
    thumbnail: pexels(15010311),
    duration: "00:10",
    sizeMb: 5.1,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Showcase video for the new signature burger.",
    uploadedBy: "Michael W.",
    uploadedAgo: "3 days ago",
    usedInPlaylists: 2,
    usedInSchedules: 8,
  },
  {
    id: "c3",
    title: "Steak Special",
    type: "image",
    format: "JPG",
    thumbnail: pexels(323682),
    duration: null,
    sizeMb: 2.4,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Hero image for the weekly steak special.",
    uploadedBy: "Amara N.",
    uploadedAgo: "4 days ago",
    usedInPlaylists: 1,
    usedInSchedules: 5,
  },
  {
    id: "c4",
    title: "Live Music Friday",
    type: "video",
    format: "MP4",
    thumbnail: pexels(7715460),
    duration: "00:20",
    sizeMb: 9.8,
    resolution: "1920×1080",
    status: "approved",
    tag: "Events",
    description: "Announcement clip for Friday's live music lineup.",
    uploadedBy: "Michael W.",
    uploadedAgo: "5 days ago",
    usedInPlaylists: 2,
    usedInSchedules: 6,
  },
  {
    id: "c5",
    title: "Morning Coffee",
    type: "image",
    format: "JPG",
    thumbnail: pexels(3632826),
    duration: null,
    sizeMb: 1.6,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Ambient morning coffee visual for breakfast hours.",
    uploadedBy: "Amara N.",
    uploadedAgo: "1 week ago",
    usedInPlaylists: 1,
    usedInSchedules: 4,
  },
  {
    id: "c6",
    title: "Cocktail Promo",
    type: "video",
    format: "MP4",
    thumbnail: pexels(9882303),
    duration: "00:12",
    sizeMb: 6.3,
    resolution: "1920×1080",
    status: "approved",
    tag: "Promotions",
    description: "Promotional video for the seasonal cocktail menu.",
    uploadedBy: "Michael W.",
    uploadedAgo: "1 week ago",
    usedInPlaylists: 2,
    usedInSchedules: 7,
  },
  {
    id: "c7",
    title: "Restaurant Ambience",
    type: "image",
    format: "JPG",
    thumbnail: pexels(776538),
    duration: null,
    sizeMb: 3.7,
    resolution: "1920×1080",
    status: "approved",
    tag: "Brand",
    description: "Brand ambience shot of the main dining room.",
    uploadedBy: "Amara N.",
    uploadedAgo: "1 week ago",
    usedInPlaylists: 0,
    usedInSchedules: 2,
  },
  {
    id: "c8",
    title: "Weekend Vibes Mix",
    type: "audio",
    format: "MP3",
    thumbnail: null,
    duration: "03:45",
    sizeMb: 8.9,
    resolution: null,
    status: "approved",
    tag: "Audio",
    description: "Upbeat weekend background audio mix.",
    uploadedBy: "Michael W.",
    uploadedAgo: "1 week ago",
    usedInPlaylists: 1,
    usedInSchedules: 3,
  },
  {
    id: "c9",
    title: "We Are Open",
    type: "video",
    format: "MP4",
    thumbnail: pexels(29964618),
    duration: "00:08",
    sizeMb: 4.6,
    resolution: "1920×1080",
    status: "approved",
    tag: "Info",
    description: "Daily opening-hours announcement clip.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 weeks ago",
    usedInPlaylists: 1,
    usedInSchedules: 9,
  },
  {
    id: "c10",
    title: "Dessert Special",
    type: "image",
    format: "JPG",
    thumbnail: pexels(132694),
    duration: null,
    sizeMb: 1.3,
    resolution: "1080×1080",
    status: "approved",
    tag: "Menu",
    description: "Featured dessert-of-the-week image.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 weeks ago",
    usedInPlaylists: 1,
    usedInSchedules: 3,
  },
  {
    id: "c11",
    title: "Sports Live Here",
    type: "video",
    format: "MP4",
    thumbnail: pexels(32285250),
    duration: "00:10",
    sizeMb: 6.8,
    resolution: "1920×1080",
    status: "approved",
    tag: "Events",
    description: "Big-screen sports announcement loop.",
    uploadedBy: "Michael W.",
    uploadedAgo: "2 weeks ago",
    usedInPlaylists: 1,
    usedInSchedules: 4,
  },
  {
    id: "c12",
    title: "Sunday Brunch",
    type: "image",
    format: "JPG",
    thumbnail: pexels(12815071),
    duration: null,
    sizeMb: 2.9,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Sunday brunch spread promotional image.",
    uploadedBy: "Amara N.",
    uploadedAgo: "3 weeks ago",
    usedInPlaylists: 0,
    usedInSchedules: 2,
  },
  {
    id: "c13",
    title: "Chill Background Mix",
    type: "audio",
    format: "MP3",
    thumbnail: null,
    duration: "05:20",
    sizeMb: 12.4,
    resolution: null,
    status: "approved",
    tag: "Audio",
    description: "Low-tempo background audio for quiet hours.",
    uploadedBy: "Michael W.",
    uploadedAgo: "3 weeks ago",
    usedInPlaylists: 2,
    usedInSchedules: 5,
  },
  {
    id: "c14",
    title: "Valentine's Dinner",
    type: "video",
    format: "MP4",
    thumbnail: pexels(1368707),
    duration: "00:20",
    sizeMb: 8.1,
    resolution: "1920×1080",
    status: "approved",
    tag: "Events",
    description: "Seasonal promotional clip for Valentine's Day dinner.",
    uploadedBy: "Amara N.",
    uploadedAgo: "1 month ago",
    usedInPlaylists: 1,
    usedInSchedules: 1,
  },
  {
    id: "c15",
    title: "Menu List – Q2 2024",
    type: "document",
    format: "PDF",
    thumbnail: null,
    duration: null,
    sizeMb: 2.1,
    resolution: null,
    status: "approved",
    tag: "Reference",
    description: "Reference copy of the Q2 2024 printed menu.",
    uploadedBy: "Michael W.",
    uploadedAgo: "1 month ago",
    usedInPlaylists: 0,
    usedInSchedules: 0,
  },
  {
    id: "c16",
    title: "Pizza Night Special",
    type: "image",
    format: "JPG",
    thumbnail: pexels(1878346),
    duration: null,
    sizeMb: 2.6,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Wood-fired pizza night promotional image.",
    uploadedBy: "Amara N.",
    uploadedAgo: "1 month ago",
    usedInPlaylists: 1,
    usedInSchedules: 3,
  },
  {
    id: "c17",
    title: "Rooftop Sunset Session",
    type: "video",
    format: "MP4",
    thumbnail: pexels(8696255),
    duration: "00:18",
    sizeMb: 10.2,
    resolution: "1920×1080",
    status: "approved",
    tag: "Ambience",
    description: "Ambient rooftop sunset loop for the golden hour.",
    uploadedBy: "Michael W.",
    uploadedAgo: "1 month ago",
    usedInPlaylists: 1,
    usedInSchedules: 2,
  },
  {
    id: "c18",
    title: "Birthday Celebration Package",
    type: "image",
    format: "JPG",
    thumbnail: pexels(34593866),
    duration: null,
    sizeMb: 3.1,
    resolution: "1920×1080",
    status: "pending",
    tag: "Events",
    description: "New promotional image for the birthday package, pending approval.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 days ago",
    usedInPlaylists: 0,
    usedInSchedules: 0,
  },
  {
    id: "c19",
    title: "Wine Tasting Evening",
    type: "video",
    format: "MP4",
    thumbnail: pexels(2838588),
    duration: "00:16",
    sizeMb: 7.9,
    resolution: "1920×1080",
    status: "approved",
    tag: "Events",
    description: "Promotional clip for the monthly wine tasting evening.",
    uploadedBy: "Michael W.",
    uploadedAgo: "1 month ago",
    usedInPlaylists: 1,
    usedInSchedules: 2,
  },
  {
    id: "c20",
    title: "Classic Birthday Cake",
    type: "image",
    format: "JPG",
    thumbnail: pexels(18131293),
    duration: null,
    sizeMb: 1.9,
    resolution: "1080×1080",
    status: "approved",
    tag: "Menu",
    description: "Birthday cake image for celebration packages.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 months ago",
    usedInPlaylists: 0,
    usedInSchedules: 1,
  },
  {
    id: "c21",
    title: "Late Night DJ Set",
    type: "video",
    format: "MP4",
    thumbnail: pexels(31694642),
    duration: "00:22",
    sizeMb: 11.3,
    resolution: "1920×1080",
    status: "approved",
    tag: "Events",
    description: "Late night DJ set teaser for the rooftop.",
    uploadedBy: "Michael W.",
    uploadedAgo: "2 months ago",
    usedInPlaylists: 1,
    usedInSchedules: 2,
  },
  {
    id: "c22",
    title: "Weekend Brunch Buffet",
    type: "image",
    format: "JPG",
    thumbnail: pexels(3465604),
    duration: null,
    sizeMb: 2.2,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Weekend buffet spread promotional image.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 months ago",
    usedInPlaylists: 0,
    usedInSchedules: 1,
  },
  {
    id: "c23",
    title: "Afternoon Coffee Break",
    type: "image",
    format: "JPG",
    thumbnail: pexels(28584802),
    duration: null,
    sizeMb: 1.4,
    resolution: "1920×1080",
    status: "approved",
    tag: "Menu",
    description: "Afternoon coffee-break promotional image.",
    uploadedBy: "Michael W.",
    uploadedAgo: "2 months ago",
    usedInPlaylists: 0,
    usedInSchedules: 1,
  },
  {
    id: "c24",
    title: "Loaded Fries Promo",
    type: "image",
    format: "JPG",
    thumbnail: pexels(27998840),
    duration: null,
    sizeMb: 2.0,
    resolution: "1920×1080",
    status: "rejected",
    tag: "Promotions",
    description: "Draft promo image — rejected pending better lighting.",
    uploadedBy: "Amara N.",
    uploadedAgo: "2 months ago",
    usedInPlaylists: 0,
    usedInSchedules: 0,
  },
];

export interface PlaylistItem {
  id: string;
  name: string;
  description: string;
  trackCount: number;
  duration: string;
  cover: string;
  zones: string[];
  status: "active" | "draft";
}

export const PLAYLISTS: PlaylistItem[] = [
  {
    id: "p1",
    name: "Evening Vibes",
    description: "Warm, mid-tempo playlist for evening dining service.",
    trackCount: 24,
    duration: "1h 42m",
    cover: pexels(776538),
    zones: ["Main Floor"],
    status: "active",
  },
  {
    id: "p2",
    name: "Rooftop Chill",
    description: "Laid-back sunset-to-night rooftop lounge audio.",
    trackCount: 18,
    duration: "1h 15m",
    cover: pexels(8696255),
    zones: ["Rooftop"],
    status: "active",
  },
  {
    id: "p3",
    name: "Soft Instrumentals",
    description: "Background instrumentals for private dining.",
    trackCount: 30,
    duration: "2h 10m",
    cover: pexels(1368707),
    zones: ["Main Floor"],
    status: "active",
  },
  {
    id: "p4",
    name: "Garden Breeze",
    description: "Light acoustic playlist for the outdoor garden.",
    trackCount: 20,
    duration: "1h 24m",
    cover: pexels(3465604),
    zones: ["Outdoor"],
    status: "active",
  },
  {
    id: "p5",
    name: "Happy Hour Mix",
    description: "Upbeat mix for the bar area during happy hour.",
    trackCount: 15,
    duration: "58m",
    cover: pexels(9882303),
    zones: ["Main Floor"],
    status: "draft",
  },
  {
    id: "p6",
    name: "Weekend Party Anthems",
    description: "High-energy anthems for weekend rooftop nights.",
    trackCount: 22,
    duration: "1h 30m",
    cover: pexels(31694642),
    zones: ["Rooftop"],
    status: "active",
  },
  {
    id: "p7",
    name: "Afrobeats Hits",
    description: "Curated Afrobeats favorites for the whole location.",
    trackCount: 24,
    duration: "1h 38m",
    cover: pexels(7715460),
    zones: ["Main Floor", "Rooftop"],
    status: "active",
  },
];
