/**
 * The tour's words. Written for someone who has never heard of Tazama:
 * plain language, concrete venue examples, one idea per step.
 */
import type { TourStep } from "./onboarding-tour";

export const TOUR_STEPS: TourStep[] = [
  {
    id: "welcome",
    chapter: "welcome",
    title: "Welcome to Tazama Business",
    body: "Tazama turns the TVs and speakers in your venues into one system you run from here — the music people hear, what shows on every screen, and how your guests join in.",
    tip: "The tour takes about three minutes. Skip it any time and replay it from the ? button.",
    targets: [],
    illustration: "welcome",
  },
  {
    id: "overview",
    chapter: "setup",
    title: "Your command center",
    body: "The Overview is your whole business at a glance: which locations are live, what's playing right now, which screens are online and what you've announced today.",
    tip: "Start your day here — anything that needs attention shows up first.",
    where: ["Overview"],
    targets: ["overview"],
    illustration: "overview",
  },
  {
    id: "locations",
    chapter: "setup",
    title: "Locations are your venues",
    body: "A location is one physical place you run — a restaurant, gym, salon, clinic or store. Everything else in Tazama, from screens to music to schedules, belongs to a location.",
    tip: "Add Location walks you through setup in five short steps.",
    where: ["Manage", "Locations"],
    targets: ["locations"],
    illustration: "locations",
  },
  {
    id: "rooms-zones",
    chapter: "setup",
    title: "Map out the space",
    body: "Split each location into zones, like Ground Floor or Terrace, and rooms inside them, like the Bar or VIP Lounge. Naming your spaces is what lets each one have its own music and content.",
    where: ["Manage", "Rooms & Zones"],
    targets: ["rooms-zones"],
    illustration: "rooms-zones",
  },
  {
    id: "screens",
    chapter: "setup",
    title: "Turn any TV into a Tazama screen",
    body: "Open Tazama on a smart TV or Android TV box and it shows a 4-digit code. Enter that code here and the screen is connected — no special hardware, no cables to run.",
    tip: "You'll always see which screens are online and what each one is playing.",
    where: ["Manage", "Screens & Devices"],
    targets: ["screens-devices"],
    illustration: "screens",
  },
  {
    id: "audio-zones",
    chapter: "setup",
    title: "Sound that moves together",
    body: "An audio zone groups the speakers in several rooms so they play the same music in perfect sync. Set a default playlist and a volume ceiling, and let the music dip automatically for announcements.",
    where: ["Manage", "Audio Zones"],
    targets: ["audio-zones"],
    illustration: "audio-zones",
  },
  {
    id: "content",
    chapter: "play",
    title: "Everything you show, in one place",
    body: "Upload the videos, images, menus and promos you want on your screens. New items can be reviewed and approved first, so nothing reaches a screen by accident.",
    where: ["Manage", "Content Library"],
    targets: ["content-library"],
    illustration: "content",
  },
  {
    id: "playlists",
    chapter: "play",
    title: "Music that fits your brand",
    body: "Build a playlist song by song, or choose a few genres and let Tazama's AI build it for you. Any playlist can play in a room, across a zone or inside a schedule.",
    tip: "A playlist's cover updates itself from its first song.",
    where: ["Manage", "Playlists"],
    targets: ["playlists"],
    illustration: "playlists",
  },
  {
    id: "schedules",
    chapter: "play",
    title: "Plan the whole day once",
    body: "A schedule splits the day into sessions — calm acoustic at 8am, upbeat hits at lunch, menu videos in the afternoon, ads in the evening. Tazama switches between them on time, every day, without anyone touching a remote.",
    where: ["Manage", "Schedules"],
    targets: ["schedules"],
    illustration: "schedules",
  },
  {
    id: "announcements",
    chapter: "play",
    title: "Speak to the whole venue",
    body: "Record a voice message or upload one, pick where it plays, and choose whether the music pauses or just lowers. Send it now, or schedule it — like “Happy hour starts in 10 minutes” every day at 4:50pm.",
    where: ["Manage", "Announcements"],
    targets: ["announcements"],
    illustration: "announcements",
  },
  {
    id: "guest-requests",
    chapter: "engage",
    title: "Guests pick the next song",
    body: "Every screen can show a QR code. Guests scan it with their phone — no app to install — and request songs that play next, with their name credited on the TV.",
    tip: "You stay in control: requests are limited per guest, and your playlist picks up right where it left off.",
    where: ["Manage", "Screens & Devices", "Guest QR"],
    targets: ["screens-devices"],
    illustration: "guest-requests",
  },
  {
    id: "live-reactions",
    chapter: "engage",
    title: "Turn the room into a crowd",
    body: "Guests who join from their phone see what's playing live and can send reactions that float across your venue's screens. It keeps people engaged — and shows you what your crowd actually loves.",
    where: ["Manage", "Audio Zones"],
    targets: ["audio-zones"],
    illustration: "live-reactions",
  },
  {
    id: "analytics",
    chapter: "measure",
    title: "See what's working",
    body: "Analytics tracks plays, reach and screen health across every location. Audience Insights shows when you're busiest and what holds attention, so your best content runs at your busiest hours.",
    where: ["Insights", "Analytics"],
    targets: ["analytics", "audience"],
    illustration: "analytics",
  },
  {
    id: "reports",
    chapter: "measure",
    title: "Reports you can share",
    body: "Performance, audience, advertising and screen-health reports, filtered by date and location and ready to download — for your team, your landlord or your advertisers.",
    where: ["Insights", "Reports"],
    targets: ["reports"],
    illustration: "reports",
  },
  {
    id: "advertising",
    chapter: "grow",
    title: "Earn from your screens",
    body: "Run campaigns for your own offers or sell screen time to other brands. An ad briefly takes over the screen and pauses the music, then hands everything back exactly where it was.",
    tip: "Inventory shows what's booked; Performance shows how every campaign is doing.",
    where: ["Advertising"],
    targets: ["advertisements", "campaigns", "ad-library", "ad-inventory", "ad-performance"],
    illustration: "advertising",
  },
  {
    id: "team",
    chapter: "grow",
    title: "Bring in your team",
    body: "Invite admins to help run everything, and managers who only see the locations they're responsible for. Billing, integrations and your business details live here too.",
    where: ["Settings", "Team"],
    targets: ["team", "billing", "integrations", "business-settings"],
    illustration: "team",
    roles: ["owner", "admin"],
  },
  {
    id: "finish",
    chapter: "finish",
    title: "You're all set",
    body: "That's Tazama Business. The quickest way to start is to add your first location, then connect a screen — the getting-started checklist on your Overview will guide you from there.",
    managerBody: "That's Tazama Business. Your Overview is the best place to start each day, and everything you just saw is one click away in the sidebar.",
    tip: "Replay this tour any time from the ? button at the top.",
    targets: [],
    illustration: "finish",
  },
];
