import {
  Activity,
  BarChart3,
  Building2,
  CalendarClock,
  Headphones,
  Hotel,
  Landmark,
  LayoutDashboard,
  Mail,
  MapPin,
  Megaphone,
  MonitorPlay,
  Music2,
  QrCode,
  ScreenShare,
  ShoppingBag,
  Stethoscope,
  Target,
  Ticket,
  Tv,
  UtensilsCrossed,
  Workflow,
  type LucideIcon,
} from "lucide-react";

import type { NavIconKey } from "@/lib/home-content";

export const NAV_ICONS: Record<NavIconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  music: Music2,
  monitor: MonitorPlay,
  megaphone: Megaphone,
  chart: BarChart3,
  calendar: CalendarClock,
  map: MapPin,
  qr: QrCode,
  target: Target,
  store: ShoppingBag,
  utensils: UtensilsCrossed,
  bag: ShoppingBag,
  hotel: Hotel,
  stethoscope: Stethoscope,
  landmark: Landmark,
  ticket: Ticket,
  workflow: Workflow,
  "screen-link": ScreenShare,
  activity: Activity,
  building: Building2,
  tv: Tv,
  mail: Mail,
  headphones: Headphones,
};
